# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import numpy as np

a = np.arange(1, 10)
print(a)
print(a[:3])
print(a[3:6])
print(a[6:])
print(a[::-1])
print(a[:-4:-1])
print(a[-4:-7:-1])
print(a[-7::-1])
print(a[::])
print(a[:])
print(a[...])
print(a[::3])
print(a[1::3])
print(a[2::3])

b = np.arange(1, 25).reshape(2, 3, 4)
print('b')
print(b)
print(b[:, 0, 0])
print(b[0, :, :])
print(b[0, ...])
print(b[0, 1])
print(b[0, 1, ::2])
print(b[..., 1])
print(b[:, 1])
print(b[0, 1, 1::2])
print(b[0, :, -1])
print(b[0, ::-1, -1])
print(b[0, ::2, -1])
print(b[::-1, ::-1])
print(b[-1, 1:, 2:])
